"""
Cloud-agnostic Airflow DAG for the complete diabetes risk pipeline.

Pipeline:

1. Data quality + preprocessing + EDA
2. Random Forest + feature importance
3. Logistic Regression + model evaluation

Person 3 models consume the model-ready dataset generated
by the Person 2 pipeline:

    data/processed/diabetes_model_ready.csv
"""

from __future__ import annotations

import os
from datetime import timedelta
from pathlib import Path

from airflow import DAG
from airflow.operators.python import PythonOperator
from pendulum import datetime

from diabetes_risk.pipeline.runner import run


# ============================================================
# PIPELINE PATHS
# ============================================================

def get_pipeline_paths() -> tuple[Path, Path, Path, str]:
    """Return dataset, processed, report and target paths."""

    input_path = Path(
        os.getenv(
            "DIABETES_DATASET_PATH",
            "data/raw/diabetes_012_health_indicators_BRFSS2015.csv",
        )
    )

    processed_dir = Path(
        os.getenv(
            "DIABETES_OUTPUT_DIR",
            "data/processed",
        )
    )

    report_dir = Path(
        os.getenv(
            "DIABETES_REPORT_DIR",
            "data/outputs",
        )
    )

    target_column = os.getenv(
        "DIABETES_TARGET_COLUMN",
        "Diabetes_012",
    )

    return (
        input_path,
        processed_dir,
        report_dir,
        target_column,
    )


# ============================================================
# TASK 1
# PERSON 2 - DATA QUALITY + PREPROCESSING + EDA
# ============================================================

def run_diabetes_pipeline() -> dict[str, object]:
    """Run the complete Person-2 data pipeline."""

    input_path, processed_dir, report_dir, target_column = (
        get_pipeline_paths()
    )

    return run(
        input_path=input_path,
        output_dir=processed_dir,
        target_column=target_column,
        report_dir=report_dir,
    )


# ============================================================
# TASK 2
# PERSON 3 - RANDOM FOREST
# ============================================================

def run_random_forest() -> dict[str, str]:
    """
    Train Random Forest using the model-ready dataset
    generated by the Person-2 preprocessing stage.
    """

    from diabetes_risk.pipeline.randomforestclassifier import (
        train_random_forest,
    )

    _, processed_dir, report_dir, _ = get_pipeline_paths()

    model_ready_path = (
        processed_dir / "diabetes_model_ready.csv"
    )

    if not model_ready_path.exists():
        raise FileNotFoundError(
            "Model-ready dataset not found: "
            f"{model_ready_path}"
        )

    return train_random_forest(
        input_path=model_ready_path,
        report_dir=report_dir,
    )


# ============================================================
# TASK 3
# PERSON 3 - MODEL EVALUATION
# ============================================================

def run_model_evaluation() -> dict[str, str]:
    """
    Evaluate Random Forest and Logistic Regression
    using the model-ready dataset.
    """

    from diabetes_risk.pipeline.model_evaluation import (
        evaluate_models,
    )

    _, processed_dir, report_dir, _ = get_pipeline_paths()

    model_ready_path = (
        processed_dir / "diabetes_model_ready.csv"
    )

    if not model_ready_path.exists():
        raise FileNotFoundError(
            "Model-ready dataset not found: "
            f"{model_ready_path}"
        )

    return evaluate_models(
        input_path=model_ready_path,
        report_dir=report_dir,
    )


# ============================================================
# AIRFLOW DAG
# ============================================================

with DAG(
    dag_id="diabetes_risk_pipeline",

    start_date=datetime(
        2026,
        1,
        1,
        tz="UTC",
    ),

    # Assignment requirement:
    # run every 2 minutes
    schedule="*/2 * * * *",

    catchup=False,

    # Prevent overlapping pipeline runs
    max_active_runs=1,

    default_args={
        "owner": "group-49-person-3",
        "retries": 1,
        "retry_delay": timedelta(
            minutes=1,
        ),
    },

    tags=[
        "diabetes",
        "assignment-1",
        "dataops",
        "person-2",
        "person-3",
    ],

    description=(
        "Complete diabetes risk data and ML pipeline "
        "running every two minutes."
    ),
) as dag:

    # --------------------------------------------------------
    # TASK 1
    # --------------------------------------------------------

    data_quality_preprocessing_and_eda = PythonOperator(
        task_id="data_quality_preprocessing_and_eda",
        python_callable=run_diabetes_pipeline,
    )

    # --------------------------------------------------------
    # TASK 2
    # --------------------------------------------------------

    random_forest = PythonOperator(
        task_id="random_forest",
        python_callable=run_random_forest,
    )

    # --------------------------------------------------------
    # TASK 3
    # --------------------------------------------------------

    model_evaluation = PythonOperator(
        task_id="model_evaluation",
        python_callable=run_model_evaluation,
    )

    # --------------------------------------------------------
    # TASK DEPENDENCIES
    # --------------------------------------------------------

    data_quality_preprocessing_and_eda >> random_forest
    random_forest >> model_evaluation
